{
  "fixes": [
      "debugAndroidTest/::core/src/test/java/",
      "debugAndroidTest/::mobile/src/test/java/"
#      "/home/runner/work/the-game-db-android-app/the-game-db-android-app>/::"
  ],
  "codecov": {
    "disable_default_path_fixes": true
  }
}