version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:

  test:
    executor:
      name: android/android-machine
    steps:
      # Checkout the code as the first step.
      - checkout
      # The next step will run the unit tests
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      # Then start the emulator and run the Instrumentation tests!
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-25;google_apis;x86

  build:
    executor: android/android
    steps:
      # Checkout the code as the first step.
      - checkout
      # Then retrieve previously downloaded dependencies
      - restore_cache:
          key: android-orb-v1-
      # Then get permission to use Gradle
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      # Then download dependency
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      # Then save downloaded dependencies to cache
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      # After that, build android project
      - run:
          name: Run Build
          command: ./gradlew build
      # and finally, save the result of a process
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  test-and-build:
    jobs:
      - test
      - build
